# default application yaml
spring:
  datasource:
    url: "jdbc:postgresql://postgres/"
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        default_schema: simple_pos
