services:
  spring_dev:
    build: .
    profiles:
      - dev
    ports:
      - 8888:8080
    volumes:
      - ./application.yaml:/app/application.yaml
  spring:
    image: ghcr.io/rainbowdashlabs/simple-pos:latest
    volumes:
      - ./application.yaml:/app/application.yaml
    profiles:
      - prod
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
