spring:
  application:
    name: simple-pos
  datasource:
    url: "jdbc:postgresql://0.0.0.0/postgres"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  jackson:
#    serialization:
#      write-date-timestamps-as-nanoseconds: true
#    deserialization:
#      read-date-timestamps-as-nanoseconds: true

server:
  port: 8888

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    root: info

security:
  jwt:
     secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
     # 1h in millisecond
     expiration-time: 3600000
     refresh-expiration-time: 604800000
