spring:
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:postgresql://0.0.0.0:5433/postgres"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
