name: Docker Build

on:
  push:
    tags:
    branches:
      - main
      - development

jobs:
  docker-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Wait for checks to succeed
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          check-name: 'Docker Build Frontend'
          running-workflow-name: 'Verify'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-frontend:${{ github.sha }}
      - name: Tag & Push branch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-frontend:${{ github.sha }}
            ghcr.io/${{ github.repository }}-frontend:${{ github.ref_name }}
      - name: Tag & Push latest image
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-frontend:${{ github.sha }}
            ghcr.io/${{ github.repository }}-frontend:latest
